# -*- coding: utf-8 -*-
"""Copy of Indian Cinema.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFH1zlQcfVmQx1AnmbYzIcM5g2mXgq4f
"""

!pip install imdbpy pandas

import pandas as pd

in_scope_ids = set()
foreign_born_ids = set()

# exclude some foriegn country identifiers
# also including US/GB/CA/AU to keep Hollywood out.
exclude_regions = {
    'US', 'GB', 'CA', 'AU',  # hollywood
    'JP', 'IT', 'ES', 'FR', 'DE', 'PT',  # common regions to exclude
    'CN', 'KR', 'RU'  # other popular film locations
}

# finding strictly indian film ids

for chunk in pd.read_csv('title.akas.tsv.gz', sep='\t', compression='gzip',
                         chunksize=500000, low_memory=False,
                         usecols=['titleId', 'region', 'isOriginalTitle']):

    # if region has IN, save it
    in_matches = chunk[chunk['region'] == 'IN']['titleId'].unique()
    in_scope_ids.update(in_matches)

    # in theory if the film is from a foreign country, its originalTitle col will be 1 for a non indian region
    foreign_matches = chunk[(chunk['region'].isin(exclude_regions)) & (chunk['isOriginalTitle'] == 1)]['titleId'].unique()
    foreign_born_ids.update(foreign_matches)

# now do films with an indian identifer minus those from another country
indian_ids = in_scope_ids - foreign_born_ids

movies_list = []
# cross check with basics to futher streamline
# look at title.basics.tsv.gz
for chunk in pd.read_csv('title.basics.tsv.gz', sep='\t', compression='gzip', chunksize=500000, low_memory=False, usecols=['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'startYear', 'genres']):

    # look for specifically movies
    in_scope = chunk[(chunk['tconst'].isin(indian_ids)) & (chunk['titleType'] == 'movie')].copy()

    # this is the important double check point
    # to get rid english films check if primaryTitle != originalTitle
    # keep if genres contains 'Musical' which is common amongst indian films
    rule_a = in_scope['primaryTitle'] != in_scope['originalTitle']
    rule_b = in_scope['genres'].str.contains('Musical', na=False)

    matches = in_scope[rule_a | rule_b]
    movies_list.append(matches)

final_movies = pd.concat(movies_list).drop_duplicates('tconst')
final_movies.replace('\\N', '').to_csv('movies.csv', index=False)
#the most filtered down method we could come up with, isnt perfect.

roles_list = []
target_tconsts = set(final_movies['tconst'])
print("Step 3: Extracting roles for verified movies...")

# Using title.principals.tsv.gz
for chunk in pd.read_csv('title.principals.tsv.gz', sep='\t', compression='gzip',
                         chunksize=500000, low_memory=False,
                         usecols=['tconst', 'nconst', 'category']):
    matches = chunk[chunk['tconst'].isin(target_tconsts)]
    roles_list.append(matches)

roles_df = pd.concat(roles_list)
roles_df.to_csv('roles.csv', index=False)
print(f"roles.csv created with {len(roles_df)} entries.")

people_list = []
target_nconsts = set(roles_df['nconst'])
#now looking at cast and crew
# Using name.basics.tsv.gz
for chunk in pd.read_csv('name.basics.tsv.gz', sep='\t', compression='gzip', chunksize=500000, low_memory=False, usecols=['nconst', 'primaryName', 'birthYear']):
    matches = chunk[chunk['nconst'].isin(target_nconsts)]
    people_list.append(matches)

final_people = pd.concat(people_list).drop_duplicates('nconst')
final_people.replace('\\N', '').to_csv('people.csv', index=False)
#extract the final people